### ISSUE TITLE
Ledger connection to dApp issue if already opened

### ISSUE THREAD

**Issue by vincentgeneste** [O3Labs/o3-dapi#13]
I'm getting an error sometimes with ledger connections:

- If I launch a dapp from the dapp browser and select a ledger account, if the app is already open on the ledger it sometimes throws an error "There was an error getting your public key. Please make sure you have the correct Ledger device connected".
- It goes away when I close that message and select the account again.
<img width="462" alt="screen shot 2019-02-04 at 16 26 06" src="https://user-images.githubusercontent.com/25534589/52248993-cb7a1000-28a5-11e9-87d8-cca39afd8355.png">

**Comment by vincentgeneste** [comment]
Still happening from time to time on desktop v2.0.1 when trying to send assets and the ledger app is already open before doing a o3dapi.NEO.send

**Comment by vincentgeneste** [comment]
It seems it's also happening when sending assets within O3 directly, so it's probably not related to the dapi..

**Comment by nickfujita** [comment]
I implemented a potential fix for the issue you were seeing, related to when transactions are denied on the ledger when received from the dapi. Please test this in the next version of the desktop application and close if resolved.

**Comment by vincentgeneste** [comment]
It seem to be resolved in the latest release :)
