### ISSUE TITLE
dApi timeout when dApp left open a couple minutes

### ISSUE THREAD

**Issue by vincentgeneste** [O3Labs/o3-dapi#16]
It seems like the event ready is fired if a dApp is left open for a couple minutes (between 5 - 10), which is triggering an unexpected getProvider() in my dApp's logic.

Not sure the reason why, could be some kind of timeout, or connectivity loss to the socket on dapi.o3.app:60003

<img width="363" alt="screen shot 2019-02-21 at 19 51 12" src="https://user-images.githubusercontent.com/25534589/53220175-f8555380-3617-11e9-856d-c9423e8c1673.png">

**Comment by nickfujita** [comment]
Seems it was due to this:
https://github.com/socketio/socket.io/issues/3259

I've updated this on desktop, and should be fixed in the next release.

**Comment by vincentgeneste** [comment]
Not happening any more in the latest release.
