### ISSUE TITLE
Add optional network fee for deploy

### ISSUE THREAD

**Issue by saltyskip** [O3Labs/o3-dapi#22]
Should function same way as invoke or send network fee, not sure if this requires changes to the wallet as well to support this functionality

Large contract deploys require a higher network fee than the minimum due to

 https://github.com/neo-project/neo-plugins/blob/master/SimplePolicy/SimplePolicy/config.json

**Comment by nickfujita** [comment]
added in https://github.com/O3Labs/o3-dapi/commit/dd588b708588f329cd02533b7883249a194cb97a

will be in desktop 2.0.5
